### ISSUE TITLE
Copyright: Localisation needs

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#1038]
Content fully exposed to localizers:

- [x] Strings on site (100% complete ✅)
- [x] Share content: variants picked by Toni/Federica are live ✅
- [x] [Audio files](https://github.com/MozillaFoundation/Advocacy/issues/1021) for recorded message to introduce phone call ✅
- [x] Social assets [Tracking progress](https://l10n.mozilla-community.org/langchecker/?locale=all&website=6&file=social/2017/copyright_sept.lang) 100% complete ✅
- [x] ~~Paid social strings~~
- [ ] Snippets [Status: strings should be exposed by Tuesday , Sept 5]
- [x] Email [Tracking progress](https://l10n.mozilla-community.org/langchecker/?locale=all&website=6&file=emails/2017/copyright_sept.lang)
- [x] Blog post - opt-in for all 5 locales (Complete so far: DE, FR, PL)

**Comment by hannahkane** [comment]
@TheoChevalier - would it be useful to make this a comprehensive ticket for all l10n needs related to the copyright campaign? Here are the things I can think of:

- [ ] Strings on site (in progress)
- [ ] Share content (waiting on EN content)
- [ ] [Audio files](https://github.com/MozillaFoundation/Advocacy/issues/1021) for recorded message to introduce phone call
- [ ] Social assets (inc. snippet?)
- [ ] Email
- [ ] Will the [media outreach plan](https://github.com/MozillaFoundation/Advocacy/issues/1037) need to be localized?

**Comment by tlasadea** [comment]
Just sharing this here too @hannahkane @TheoChevalier. The copy for snippets & social is [here](https://docs.google.com/a/mozilla.com/document/d/12m4sc3mfxVHL-lM8_aQlBDhfek6q4WBdcsxAIiximMM/edit?usp=sharing)

**Comment by TheoChevalier** [comment]
To clarify, I’m exposing social content now, but am waiting for snippets to be approved to get them localized

**Comment by TheoChevalier** [comment]
Share content: shipping variants picked by Toni, Federica and myself for all locales but English: https://github.com/mozilla/copyright/pull/111

**Comment by hannahkane** [comment]
@TheoChevalier - do you have what you need for the paid social strings?

**Comment by TheoChevalier** [comment]
@hannahkane Not yet, but I think @tlasadea is on it

**Comment by tlasadea** [comment]
Oui!

Also - paid social for other countries/locales other than UK/EN will go
live earliest Tuesday due to Alex capacity/labour day holiday.

I need to see the creative for the paid social stuff, so hoping
@natalieworth will finish today so I can pop those over.

**Comment by TheoChevalier** [comment]
Updated the first post, but making it more clear here — the website is now fully translated

**Comment by TheoChevalier** [comment]
@tlasadea Hey Temi, any update on the copy? I’m tempted to say we’re too late

**Comment by tlasadea** [comment]
Hey @theochevalier - we may be.

I'm having a call with Alex this arvo UK time to discuss - he thinks
there's too many splits/audiences so I'm tempted to just run UK.

I'll let you know later, working through an email of his rn.

*Temi Lasade-Anderson*
Social Media Specialist
Mozilla Foundation
Slack: tlasade | Twitter: @temilasade <http://www.twitter.com/temilasade>

**Comment by tlasadea** [comment]
@hannahkane @TheoChevalier just reiterating that localisation for paid social is not needed. We're just waiting on snippet approval now.

**Comment by hannahkane** [comment]
Now that we're about to start promoting the copyright site, I'm wondering if this ticket is still valid. Are we still working towards snippet approval and localization?

**Comment by tlasadea** [comment]
Hm let me check in with Wes on Snippet. I don't think we have a date for that yet. @TheoChevalier not sure what the update is on localization?

**Comment by TheoChevalier** [comment]
@tlasadea IIRC, we said we didn’t need to update the copy?
Translations are here https://l10n.mozilla-community.org/langchecker/?website=6&file=snippets/2017/copyright_sept.lang&action=translate&show

**Comment by hannahkane** [comment]
I'm thinking we can close this ticket, based on the above. Please re-open if that's not true.
