### ISSUE TITLE
Meta video delivery ticket

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/Advocacy#330]
Video 1 (explainer):
- [x] Edit complete
- [x] Edit approved
- [x] Versioning complete
- [x] Output and delivery complete

Video 2 (meme jail):
- [x] Edit complete
- [x] Edit approved
- [x] Versioning complete
- [x] Output and delivery complete

Video 3 (CSI GIF)
- [x] Edit complete
- [x] Edit approved
- [x] Versioning complete
- [x] Output and delivery complete

**Comment by natalieworth** [comment]
Final Assets for Meme Jail video are here: https://drive.google.com/drive/u/1/folders/0B20-0lpP23c0RVd2V2RWbzI2QjA

Final Assets for CSI:GIF are here: https://drive.google.com/drive/u/1/folders/0B20-0lpP23c0dEJSM3A5U0VNUjg

**Comment by brettgaylor** [comment]
Final assets for A Meme Is Born!!!
https://drive.google.com/drive/u/1/folders/0B20-0lpP23c0NkJBd00wVkNUYmc

**Comment by brettgaylor** [comment]
@HPaulJohnson This spreadsheet is being updated with appropriate formats for each platform
https://docs.google.com/spreadsheets/d/1rmqeIJq1vMDFsI0sicu7XdVwkLDur-rerTPb3rjFyko/edit#gid=0

**Comment by natalieworth** [comment]
@HPaulJohnson Spreadsheet is complete! Label mov-format/ mp4-format and posted facebook, youtube, and instagram (after scrolling down the page): https://docs.google.com/spreadsheets/d/1rmqeIJq1vMDFsI0sicu7XdVwkLDur-rerTPb3rjFyko/edit#gid=0

**Comment by natalieworth** [comment]
Here's the documented changes filed in the 2 bugzilla tickets from our localizers:
https://bugzilla.mozilla.org/show_bug.cgi?id=1302491
Video 2
At 0:01 "Según laley de derechos de autorde la UE" should be "Según la ley de derechos de autor de la UE" ( "laley" and "autorde" should be two separate words).
<img width="425" alt="screen shot 2016-09-19 at 9 27 03 am" src="https://cloud.githubusercontent.com/assets/14876567/18642133/589845e6-7e54-11e6-82cf-c56a3ece2171.png">

https://bugzilla.mozilla.org/show_bug.cgi?id=1302497
For German:
At 0:52, the subtitle is "Wir brauchen Gesetze Urheberrecht" but should be "Wir brauchen Gesetze zum Urheberrecht".
In general, the audio feels packed and fast, generating some stress (e.g. there is usually a break after someone ends a sentence, but not here; in the future, slowing down the video might be an idea to consider).
<img width="424" alt="screen shot 2016-09-19 at 10 02 38 am" src="https://cloud.githubusercontent.com/assets/14876567/18642155/6e47e766-7e54-11e6-9735-bc74d12c1d9e.png">

For French:
At 0:55, "le droit d’auteur adaptée à" should be "le droit d’auteur adaptées à".
At 1:04, "au 21ème siècle" should be "au 21e siècle".
At 1:08, "Agissons pour que le droit d’auteur européen s’adapte au 21ème siècle." should be "Agissons pour que le droit d’auteur européen s’adapte au 21e siècle."
<img width="426" alt="screen shot 2016-09-19 at 10 09 48 am" src="https://cloud.githubusercontent.com/assets/14876567/18642181/7deed044-7e54-11e6-931e-1d96c8f85e21.png">
<img width="426" alt="screen shot 2016-09-19 at 10 09 58 am" src="https://cloud.githubusercontent.com/assets/14876567/18642183/80b9cf36-7e54-11e6-8a9f-84f0e63eec6d.png">

For ES:
At 00:44 "...no está permitido." should be "no está permitido."  (without initial ellipsis to keep subtitle formats consistent.)
To improve readability, the font size should be smaller, allowing to fit 42 characters across the screen — the standard in subtitling.
<img width="425" alt="screen shot 2016-09-19 at 10 19 31 am" src="https://cloud.githubusercontent.com/assets/14876567/18642205/92928c02-7e54-11e6-965c-a9be98d261a5.png">

**Comment by natalieworth** [comment]
Languages and subtitles have been updated based on the localizer's feedback:
Final files in .mov, .mp4, and Webm are here: https://drive.google.com/drive/u/1/folders/0B20-0lpP23c0QjBOaklOOWdkMnM
cc @damiankay @brettgaylor @cadecairos
