### ISSUE TITLE
Copyright Petition: Outstanding issues meta ticket

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#503]
Detailed description of work:
Hoping to make a log of any outstanding issues to get a clear sense of whether we can launch the V2 Petition on Monday. 

Can everyone please take a few minutes to review the site, and log any issues that aren't identified below before EOW today? 

[Copyright V2 staging](http://mozillafoundationstaging-mozillafoundation.nationbuilder.com/)
- [x] Add localized footer links #500 
- [x] Add localized cat GIF #434 
- [x] Add localized copy for "Let's go"  
- [x] Update meta data #502 

This will help to identify if there are any blockers for launch. 

_Start date: September 23, 2016_ 
_Due date: September 23, 2016_ 

CC: @brettgaylor @lovegushwa @HPaulJohnson @natalieworth @valianttry 

Thanks!

**Comment by vojtechmzl** [comment]
Labels in the first two fields of the form are not translating for me in Firefox (FIrst Name, Last Name)

![screen shot 2016-09-23 at 2 48 42 pm](https://cloud.githubusercontent.com/assets/20688240/18802302/dafd9554-819c-11e6-8b63-14c14f582594.png)

**Comment by vojtechmzl** [comment]
The Czech disclaimer below the form has the word information twice in it, once as a plan text, once as a link.

![screen shot 2016-09-23 at 2 49 16 pm](https://cloud.githubusercontent.com/assets/20688240/18802352/0c67e4e6-819d-11e6-9f67-c86b6bfb9efb.png)

**Comment by HPaulJohnson** [comment]
there is a paragraph of text in 3rd section that is not translated in French. As far as I can tell this is isolated to French and all other languages are translated as expected. 

![untranslated](https://cloud.githubusercontent.com/assets/10078715/18802476/db89b4c0-819d-11e6-9e6b-2b95f8782ce5.jpg)

**Comment by HPaulJohnson** [comment]
Nyan cat is still is english only. This issue is tracked in another QA ticket #434

**Comment by damiankay** [comment]
All resolved
