### ISSUE TITLE
EU net neutrality savetheinternet.eu campaign planning overview

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#58]
**Tasks and Timeline:**
- [x] Thursday June 9 9:00pm PST GMT -8:00 (San Francisco): Draft EN-US snippet language ready for stakeholder review #57 
- [x] Friday June 10 12noon PST GMT -8:00 (San Francisco): Final EN-US snippet language approved by all stakeholders (Marketing, Policy, Legal) 
- [x] Friday June 10 5pm PST GMT -8:00 (San Francisco): Final EN-US snippet language shared with L10N (specifically Peiying Mo pmo@mozilla.com  is leading). Final language will go here, and then inserted into Pontoon: https://github.com/mozilla-l10n/engagement-l10n 
- [x] Monday June 13 12 noon GMT+1 (Local London Time): Final localized snippet language due to snippet team for setting up snippets for target locales 
- [x] Launch snippet in P1 locales: Tue June 14, 2016 5pm GMT+1 (Local London Time) (can be pushed to Wed June 15 if necessary)

Audience description: Firefox users 
Localization: P1:  German, French, Spanish, Italian, English (GB); P2: Bulgarian, Slovenian, Romanian 
Landing page when people click the snippet:
Localized take action form, e.g.:
English: http://savetheinternet.eu/en/#send-a-message 
German: http://savetheinternet.eu/de/#send-a-message 
French: http://savetheinternet.eu/fr/#send-a-message 
Spanish: http://savetheinternet.eu/es/#send-a-message 
Italian: http://savetheinternet.eu/it/#send-a-message 

**Additional background from @shaghdoosti** 
we can have a lot of impact, but given the tight timeline the only way to be able to have that impact is if we use the website of savetheinternet.eu, coalition partners that we have previously worked with. We’re looking for your thumbs up to go ahead with getting the site into the snippet. 

**Here’s the longer version:** 

**Context:** Last year the EU passed legislation around NN for all of the EU. They delegated BEREC (the collection of telecoms regulators in the EU) to come up with enforcement guidelines for countries around implementing the law. 

Why we can have impact: BEREC are holding a public consultation on this issue until July 18. Which is a tight timeline.  The reason we’d love to get something in the snippet as soon as possible is they’ve released what are pretty good guidelines already. They’ll be getting increasing amounts of pressure from the telcos and other net neutrality foes to weaken and undermine them. As a regulatory body, BEREC isn’t usually a target for advocacy actions --  making sure a lot of people take part in the consultation process will give BEREC ammunition to stand their ground and might even help make the guidelines better. Even though the deadline is mid July these conversations are happening now and we want to make sure that we get a tipping point of public support before decisions are final. 

We will put savetheinternet.eu website in the snippet to help increase the number of people making submissions to Berec. The policy team has reviewed the site and have approved the language -- Marshall and the legal team have reviewed the site from a compliance stand point and have suggested some changes that we’re currently working with the savetheinternet.eu team to fix.

**Comment by KevZawacki** [comment]
@valianttry 

Noting that we also did external comms around this -- I worked with Raegan [on a blog](https://blog.mozilla.org/netpolicy/2016/06/20/eu-users-can-stand-up-for-net-neutrality/) (posted this morning) and [promotion on social](https://twitter.com/mozilla/status/744873228313763840). I will also be reaching out to EU press today.
