### ISSUE TITLE
6/28 Codemoji launch checklist

### ISSUE THREAD

**Issue by KevZawacki** [MozillaFoundation/Advocacy#63]
- [x] Brett and Jordan on project call (6/27) 
- [x] Send all MoFo email (6/27)
- [x] Post announcement to blog.mozilla.org and Medium.com/encryption-matters
- [x] Create coverage report 
- [x] Alert PR global and ML
- [x] Begin social promotion
- [x] Pitch media
- [x] Pitch influencers

**Comment by KevZawacki** [comment]
Pitching and social will continue this week and next, but preliminary launch activities are complete. Closing ticket.

Currently at 38 stories in 9 countries, and >2,300 conversations on Twitter.

cc @brettgaylor
