### ISSUE TITLE
Ship Codemoji

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#7]
**Launch Checklist:** 
- [x] TODO delivers final changes to MoFo (5/20)
- [x] Optimize landing page version for Codemoji traffic #11 (5/20)
- [x] @ScottDowne / @cadecairos move Codemoji to advocacy.mozilla.org website #38 (5/23)
- [x] QA Codemoji and landing page (5/23)
- [ ] User testing via email #26 (~5/26)
- [ ] Evaluate feedback from email test & determine next steps (5/31)
- [ ] Begin broader marketing push, if deemed appropriate #12 (~6/6)

**Project Overview:**

Goal is to ship Codemoji and begin promotional activities in Q2 to extend our advocacy work on encryption.

We've submitted a final round of changes to TODO and are awaiting a final change order for this work.

At this point the assumption is that we can soft launch on 5/25, do some small scale testing via email and be ready to more widely promote in the second half of June. 

We are working with the MoCo social and durable teams on the wider promotional plan for Codemoji. 

cc: @lovegushwa

**Comment by HPaulJohnson** [comment]
Final set of changes outlined here: 
https://docs.google.com/presentation/d/1J7L6JfLgSnoZtufbUnBjA7QmvyWTgIp_uMH2XuEDrO4/edit#slide=id.gd58133b56_0_69

These have have been reviewed with TODO and we are processing change order now. Aiming to have this live by 5/25.

**Comment by HPaulJohnson** [comment]
added launch checklist in project overview comment above ^

**Comment by ScottDowne** [comment]
Closing this.

Given the state of codemoji, anything we didn't do would be better served in new tickets.
