### ISSUE TITLE
QA checklist for Copyright site 

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#724]
Staging: https://changecopyright-org-staging.herokuapp.com/en-US/

## Devices
 - [x] Desktop
 - [x] Tablet
 - [x] Mobile

## Browsers (latest version of each)
 - [x] FF
 - [x] Chrome
 - [x] IE
 - [x] Safari

## Front end functionality to test
 - [x] All links work as expected (including Privacy and Terms in form, all footer links)
 - [x] Navigation works as expected (including "Get Involved" button in hero)
 - [x] Sign-up form works as expected 
   - [x] field highlights work
   - [x] tabbing through fields works correctly (desktop)
   - [x] user receives error message if they don't provide an email
   - [x] user cannot submit form with either or both checkboxes unchecked
  -  [x] user lands on ShareProgress page (EN-only) after submitting form
  -  [x] ShareProgress works as expected

## Backend functionality to test
  - [x] Users info is added to Salesforce, is properly tagged ( @stephaniemcv to check this box )
  - [x]  Ensure urls for tracking and signup are correct and match the production url. ( @ScottDowne to check this box)

## Design QA
  - [x] Production matches comps ( @beccaklam to check this box )

## Localization QA
 - [x] Language selector works as expected
 - [x] Pages inc. content, form submission, and Share functionality work as expected in all locales ( @TheoChevalier to check this box )

**Comment by hannahkane** [comment]
Starting a draft QA script in this ticket. More will be added after the Resources page is designed. 

Once this script is agreed upon, we can figure out how to divide up the QA process (e.g. by designating individuals to run through the script in different combinations of device/browser/language, to ensure full coverage).

Note: not including any detail about design QA here, because I wasn't sure if there's a separate process you already have for that?

cc @shaghdoosti @lovegushwa @beccaklam @ScottDowne @TheoChevalier

**Comment by ScottDowne** [comment]
There is something I want to make sure I don't forget.

The site has a couple places that need to use the page url (metrics, signup) for tracking reasons. So:

- [x] Ensure urls for tracking and signup are correct and match the production url.

**Comment by hannahkane** [comment]
Updated the first comment in this ticket to reflect what I know of the current state of QA. Added @stephaniemcv @beccaklam @ScottDowne and @TheoChevalier as responsible for certain aspects of QA. Let's not give Chris the OK to push the button on the url switch until everyone here has signed off.

**Comment by ScottDowne** [comment]
- [x] Make sure all share progress links are updated with prod values once we're ready to ship.

**Comment by ScottDowne** [comment]
Just two more checkboxes, but I think we're good on my end.

**Comment by hannahkane** [comment]
We can do it! @beccaklam and @TheoChevalier - is anything blocking you from checking your respective boxes in the original comment?

**Comment by TheoChevalier** [comment]
Checked mine a few minutes ago, but I’ll do some more checking after latest PR from @beccaklam is merged :)

(Found one small issue with Spanish, the Get Involved button is in English. Not a technical issue, reached out to the localizer so that she can have a look)

**Comment by ScottDowne** [comment]
@TheoChevalier Becca's changes have landed.

**Comment by TheoChevalier** [comment]
Everything looks good :) 🚀
