### ISSUE TITLE
Deployment checklist and Emergency Response plan

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#756]
Since we're launching this campaign on a weekend, it seems like we should have both a deployment checklist and an emergency response plan in place. Here are some initial thoughts.

### Wednesday
 - [X] Staging site deployed
 - [X] update the DNS settings, but disable the CloudFront CDN from serving the site (@cade - this is already done, right?)
 - [X] begin QA

### Thursday
 - [x] QA + fixes

### Friday
 - [x] QA passes (close all [tickets with QA in the title](https://github.com/MozillaFoundation/Advocacy/issues?utf8=%E2%9C%93&q=is%3Aopen%20label%3A%22Open%20Data%20Day%20petition%20site%22%20QA%20))
 - [x] Snippet scheduled
 - [x] Email scheduled
 - [x] enable CloudFront CDN - do we have a time?

### Saturday
 - [x] Snippet live - time?
 - [x] Email sent - 8:30am ET
 - [x] someone to sanity check during the day, by confirming that signatures are coming in (@hannahkane will confirm the snippet is live, and that signatures are coming in via the google sheet. @HPaulJohnson will check out analytics)

## Emergency Response plan
 - [ ] will follow [typical emergency protocol](https://github.com/mozillafoundation/mofo-devops/#on-call-emergencies) if needed

**Comment by cade** [comment]
Try as you may to fix the @ mentions, you still won't be rid of me...

Also, weekend rollouts? I hope Mozilla's dropping that time-and-a-half pay on y'all.

![weekend-deployments](https://cloud.githubusercontent.com/assets/3403/23488577/330d80d6-feb3-11e6-849b-496500279d52.gif)

**Comment by ScottDowne** [comment]
lol, @cade strikes again.

**Comment by ScottDowne** [comment]
@hannahkane Yeah, I won't be too far from my email/computer this weekend.

**Comment by hannahkane** [comment]
sorry, @cade. :) Are you keeping track? I hope I'm not the worst offender.

**Comment by cade** [comment]
> Are you keeping track?

The 🍺 list grows...

**Comment by stephaniemcv** [comment]
@hannahkane I'm flying that day, so it'll be spotty. @drewmoto, would it be possible to back me up?

**Comment by cadecairos** [comment]
> update the DNS settings, but disable the CloudFront CDN from serving the site (@cade - this is already done, right?)

Yes!


> should we just use the normal emergency protocol? Can you link to that here, or describe it, so we know what to do if something goes wrong? @ScottDowne - will you be available on Saturday in the unlikely event that something fails?

https://github.com/mozillafoundation/mofo-devops/#on-call-emergencies

I'll be available to respond to any incidents, all weekend.

**Comment by hannahkane** [comment]
Updated original comment to reflect the latest plan.

**Comment by drewmoto** [comment]
@stephaniemcv I can back you up. What days specifically and what are the 'worst case scenarios' I am keeping an eye out for (and hopefully have a fix ready)?

**Comment by hannahkane** [comment]
We totally did this.
