### ISSUE TITLE
Deployment / Promotion schedule

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#769]
Hey @shaghdoosti @ScottDowne @lovegushwa @beccaklam @WillatMozFdn - does this reflect what we just talked about?

@TheoChevalier - does this localization schedule seem reasonable to you?

Design:
 - [x] Tuesday: Share page #770

Build
 - [x] Tues/Wed/Thurs: Share page #767
 - [x] Tues/Wed/Thurs: Checkboxes #768 

Localize:
 - [x] Wed/Thurs (March 8, 9): Share page (#767) and Checkboxes (#768)

QA (#724):
 - [x] Thursday (March 9)

Deploy:
 - [x] Friday, March 10: "basic" sign-up version with share page, localized

Promotion:
- [ ] TBD: Snippet
- [ ] TBD: other stuff TBD

**Comment by hannahkane** [comment]
As per meeting with email team: we've decided this campaign doesn't require an email promotion, since the purpose is to collect new emails. Removing references to the "alternate version" in the checklist above.

**Comment by TheoChevalier** [comment]
@hannahkane What’s the alternate version? Hard to answer without visibility of what’s coming :) Is it a complete copy change, just the CTA for people coming from email, or something else?

Otherwise, the rest look good to me. Note that as of now, we have 80% completion on the EU locales https://pontoon.mozilla.org/projects/copyright-campaign/

**Comment by hannahkane** [comment]
@TheoChevalier - Was going to be a version of the site that we'd make visible to people coming from the email campaign, with potentially a different CTA (other than "sign up"). But in a very recent discussion, we decided to simply not do an email campaign around this, and instead focus our outreach on attracting new email sign-ups. So...no alternate version needed after all.

**Comment by TheoChevalier** [comment]
@hannahkane Ok, thanks for the update. So, if we’re not rewriting the entire copy, everything looks good to me.

**Comment by hannahkane** [comment]
Closing because only outstanding item is snippet which is tracked elsewhere.
