### ISSUE TITLE
News Matrix Release Plan

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#798]
@caltrider @lovegushwa @beccaklam @ScottDowne @WillatMozFdn @vojtechmzl - please add to this ordered list if there are other items.

### Week ending April 7:
 - [x] News Matrix design finalized (#781 - @lovegushwa)
 - [x] Choose a thinglink account (#795 - @ScottDowne, @caltrider)
 - [x] Content for News Matrix 1 finalized, first matrix created, shared on Reddit, etc (#796 - @caltrider)
 - [ ] <s>Choose a domain</s>, and purchase it (will be discussed off github)
 - [x] Build news matrix landing page (#786 @beccaklam @ScottDowne)
 - [x] QA landing page (#805 - @hannahkane)
 - [ ] Legal review of matrix landing page ( @caltrider )

### Week ending April 14
 - [ ] Content for News Matrix 2 finalized, matrix created (#797 - @caltrider, maybe with an assist since she'll be in Toronto)
 - [ ] News Matrix 1 and 2 added to matrix landing page (my understanding is that @caltrider will be able to do this in the future, but for this week, when she's in Toronto, others will need to help)
 - [ ] Finalize email template and build email for second matrix ( @WillatMozFdn )

**Comment by caltrider** [comment]
@hannahkane couple things.  I'm currently talking to legal about the news matrix. Maybe let's not confuse them too much with multiple asks on this just yet.

Second, I'm in Toronto next week for the OKR #3 Summit!  I plan to curate and write the matrix, any help I can get posting and such will be appreciated as I'll be traveling most of the day Thursday.

**Comment by hannahkane** [comment]
@caltrider - cool. I put your name as responsible for the legal review (would be great to get their eyes on the site itself before we launch, to make sure we have their OK on the form/checkboxes).

I'm sure we can handle the posting of the matrix while you're in Toronto. Thanks for the heads up!

**Comment by hannahkane** [comment]
This ticket no longer feels useful, so I'm going to close.

Remaining work is ticketed.
