### ISSUE TITLE
Feature complete sandbox

### ISSUE THREAD

**Issue by ScottDowne** [MozillaFoundation/Advocacy#85]
This is complete when the features and pages listed below is done:
- [ ] A list of pages defined here: #82
- [ ] A list of features defined here: #75
- [ ] Integrated with crm and signup: #80 

It needs to look complete and works as expected from a user point of view. If back end bits are not hooked up and faked, that's fine.

**Comment by ScottDowne** [comment]
Likely Fission does this, but for now, just pushing to next HB.
