### ISSUE TITLE
QA makerparty/nationbuilder sandbox

### ISSUE THREAD

**Issue by ScottDowne** [MozillaFoundation/Advocacy#87]
Take the finished sandbox created here: https://github.com/MozillaFoundation/Advocacy/issues/86

And do QA

Need to get feedback from consulted stakeholders, and show to informed people

Let's also figure out a list of things to qa.

We can start with going over:
- [ ] A list of pages defined here: #82
- [ ] A list of features defined here: #75
- [ ] Integrated with crm and signup: #80 
- [ ] copy defined here: https://github.com/MozillaFoundation/Advocacy/issues/84
- [ ] comps created here: https://github.com/MozillaFoundation/Advocacy/issues/81

**Comment by ScottDowne** [comment]
We can file another QA ticket for next week and do another round of QA if needed.
